# Generated by Django 2.0.7 on 2018-07-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatLng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latit', models.FloatField()),
                ('longi', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X_WGS84', models.FloatField()),
                ('Y_WGS84', models.FloatField()),
                ('X_local', models.FloatField(blank=True, null=True)),
                ('Y_local', models.FloatField(blank=True, null=True)),
                ('controlType', models.CharField(blank=True, max_length=200)),
                ('controlClass', models.CharField(blank=True, max_length=200)),
                ('catalog_number', models.CharField(blank=True, max_length=200)),
                ('hAmsterdam', models.FloatField(blank=True)),
                ('hKronsztadt', models.FloatField(blank=True)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('district', models.CharField(blank=True, max_length=200)),
                ('county', models.CharField(blank=True, max_length=200)),
                ('locality', models.CharField(blank=True, max_length=200)),
                ('city_district', models.CharField(blank=True, max_length=200)),
                ('road', models.CharField(blank=True, max_length=200)),
                ('house_number', models.CharField(blank=True, max_length=200)),
                ('stabilization', models.CharField(blank=True, max_length=200)),
                ('found', models.BooleanField()),
            ],
        ),
    ]
