# Generated by Django 2.0.7 on 2018-09-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osnowa_app', '0003_auto_20180729_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='catalog_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='city_district',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='controlClass',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='controlType',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='county',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='district',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='hAmsterdam',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='hKronsztadt',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='house_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='locality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='road',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='stabilization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
