# Generated by Django 2.0.7 on 2018-10-14 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osnowa_app', '0006_auto_20181003_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.RemoveField(
            model_name='point',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osnowa_app.Point'),
        ),
    ]
