# Generated by Django 2.0.9 on 2018-12-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osnowa_app', '0007_auto_20181014_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='found',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
